set(before "${BINARY_DIR}/lineage-before.json")
set(after "${BINARY_DIR}/lineage-after.json")
set(request "${BINARY_DIR}/lineage-request.json")
execute_process(COMMAND "${EXTRACTOR}" --source-revision old --configuration arm
    "${SOURCE_DIR}/tests/fixtures/lineage_before.cpp" -- -std=c++17
    OUTPUT_FILE "${before}" RESULT_VARIABLE result)
if(NOT result EQUAL 0)
    message(FATAL_ERROR "before extraction failed")
endif()
execute_process(COMMAND "${EXTRACTOR}" --source-revision new --configuration arm
    "${SOURCE_DIR}/tests/fixtures/lineage_after.cpp" -- -std=c++17
    OUTPUT_FILE "${after}" RESULT_VARIABLE result)
if(NOT result EQUAL 0)
    message(FATAL_ERROR "after extraction failed")
endif()
file(WRITE "${request}" "{\"schema_version\":1,\"query\":\"lineage.transition\",\"params\":{\"before\":\"${before}\",\"after\":\"${after}\"}}")
execute_process(COMMAND "${REPOTRAVERSE}" query --request "${request}"
    OUTPUT_VARIABLE response RESULT_VARIABLE result)
if(NOT result EQUAL 0)
    message(FATAL_ERROR "lineage query failed: ${response}")
endif()
foreach(expected "moved_and_renamed" "\"content_change\":\"none\"" "\"automatically_resolved\":true")
    string(FIND "${response}" "${expected}" found)
    if(found EQUAL -1)
        message(FATAL_ERROR "missing ${expected}: ${response}")
    endif()
endforeach()
file(WRITE "${request}" "{\"schema_version\":1,\"query\":\"element.history_stats\",\"params\":{\"bundles\":[\"${before}\",\"${after}\"]}}")
execute_process(COMMAND "${REPOTRAVERSE}" query --request "${request}"
    OUTPUT_VARIABLE response RESULT_VARIABLE result)
if(NOT result EQUAL 0)
    message(FATAL_ERROR "history statistics query failed: ${response}")
endif()
foreach(expected "\"content_changed_transitions\":0" "\"moved_transitions\":1" "\"renamed_transitions\":1")
    string(FIND "${response}" "${expected}" found)
    if(found EQUAL -1)
        message(FATAL_ERROR "missing ${expected}: ${response}")
    endif()
endforeach()
